version: 2
updates:
  - package-ecosystem: "terraform"
    directories: ["/shared", "/envs/*", "/modules/*"]
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
